module.exports = {
  apps: [
    {
      name: 'newsar',
      script: '.output/server/index.mjs',
      cwd: '/var/www/newsar.codejungle.org',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3050,
        ADMIN_USERNAME: process.env.ADMIN_USERNAME || 'admin',
        ADMIN_PASSWORD: process.env.ADMIN_PASSWORD || '',
        DATABASE_URL: process.env.DATABASE_URL || 'postgresql://newsar:password@localhost:5432/newsar',
        POSTGRES_HOST: process.env.POSTGRES_HOST || 'localhost',
        POSTGRES_PORT: process.env.POSTGRES_PORT || '5432',
        POSTGRES_DB: process.env.POSTGRES_DB || 'newsar',
        POSTGRES_USER: process.env.POSTGRES_USER || 'newsar',
        POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD || '',
        // Gemini API (fallback only)
        GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
        GEMINI_MODEL: process.env.GEMINI_MODEL || 'gemini-2.5-flash-lite',
        GEMINI_BATCH_MODEL: process.env.GEMINI_BATCH_MODEL || 'gemini-2.5-flash-lite',
        FORCE_GEMINI: process.env.FORCE_GEMINI || 'true',
        // Claude API for classification/analysis (fallback)
        ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY || '',
        CLAUDE_MODEL: process.env.CLAUDE_MODEL || 'claude-3-5-haiku-20241022',
        // Local Ollama (embeddings only, chat via Gemini)
        OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL || 'http://localhost:11434',
        OLLAMA_EMBED_MODEL: process.env.OLLAMA_EMBED_MODEL || 'nomic-embed-text',
        OLLAMA_CHAT_MODEL: process.env.OLLAMA_CHAT_MODEL || 'llama3.2:3b',
        OLLAMA_TIMEOUT: process.env.OLLAMA_TIMEOUT || '180000',
        RUNPOD_ENABLED: process.env.RUNPOD_ENABLED || 'false',
        NUXT_PORT: '3050',
        NUXT_HOST: '0.0.0.0',
        NUXT_SESSION_PASSWORD: process.env.NUXT_SESSION_PASSWORD || '',
        BULLMQ_QUEUE_NAME: 'newsar-jobs',
        BULLMQ_TOPIC_QUEUE_NAME: 'newsar-topic-jobs',
        BULLMQ_CONCURRENCY: '2',
        // Stock market API keys
        FINNHUB_API_KEY: process.env.FINNHUB_API_KEY || '',
        ALPHAVANTAGE_API_KEY: process.env.ALPHAVANTAGE_API_KEY || '',
        ALPACA_API_KEY: process.env.ALPACA_API_KEY || '',
        ALPACA_API_SECRET: process.env.ALPACA_API_SECRET || '',
      },
      error_file: '/var/log/pm2/newsar-error.log',
      out_file: '/var/log/pm2/newsar-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
    {
      name: 'newsar-worker',
      script: 'node_modules/.bin/tsx',
      args: 'server/workers/feedWorker.ts',
      cwd: '/var/www/newsar.codejungle.org',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        DATABASE_URL: process.env.DATABASE_URL || 'postgresql://newsar:password@localhost:5432/newsar',
        POSTGRES_HOST: process.env.POSTGRES_HOST || 'localhost',
        POSTGRES_PORT: process.env.POSTGRES_PORT || '5432',
        POSTGRES_DB: process.env.POSTGRES_DB || 'newsar',
        POSTGRES_USER: process.env.POSTGRES_USER || 'newsar',
        POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD || '',
        REDIS_HOST: process.env.REDIS_HOST || 'localhost',
        REDIS_PORT: process.env.REDIS_PORT || '6379',
        REDIS_PASSWORD: process.env.REDIS_PASSWORD || '',
        // Gemini API (fallback only)
        GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
        GEMINI_MODEL: process.env.GEMINI_MODEL || 'gemini-2.5-flash-lite',
        GEMINI_BATCH_MODEL: process.env.GEMINI_BATCH_MODEL || 'gemini-2.5-flash-lite',
        FORCE_GEMINI: process.env.FORCE_GEMINI || 'true',
        // Claude API for classification/analysis (fallback)
        ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY || '',
        CLAUDE_MODEL: process.env.CLAUDE_MODEL || 'claude-3-5-haiku-20241022',
        // Local Ollama (embeddings only, chat via Gemini)
        OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL || 'http://localhost:11434',
        OLLAMA_EMBED_MODEL: process.env.OLLAMA_EMBED_MODEL || 'nomic-embed-text',
        OLLAMA_CHAT_MODEL: process.env.OLLAMA_CHAT_MODEL || 'llama3.2:3b',
        OLLAMA_TIMEOUT: process.env.OLLAMA_TIMEOUT || '180000',
        RUNPOD_ENABLED: process.env.RUNPOD_ENABLED || 'false',
        BULLMQ_QUEUE_NAME: 'newsar-jobs',
        BULLMQ_CONCURRENCY: '1',
        // Disable Transformers.js - use Ollama for better quality
        USE_TRANSFORMERS_FOR_NER: 'false',
        USE_TRANSFORMERS_FOR_SENTIMENT: 'false',
        USE_TRANSFORMERS_FOR_KEYWORDS: 'false',
        USE_TRANSFORMERS_FOR_SUMMARY: 'false',
      },
      error_file: '/var/log/pm2/newsar-worker-error.log',
      out_file: '/var/log/pm2/newsar-worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '300M',
    },
  ],
}
